version: "3.4"

services:
    poste:
        image: analogic/poste.io
        restart: always
        network_mode: "host"
        volumes:
            - /root/mail-data/:/data
        environment:
            - HTTPS=ON
